global:
  resolve_timeout: 3m

route:
  receiver: 'discord'

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1265616329667514370/ewBL6QCDM0faacg7GZ_bCvUt_k362qBzFzEMUnC83Dw6hVhT36Z8qpRThPeC-rDwPJRr'
